config/routes.rb
ElevatorPitch::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  get 'pitches/:identifier', :to => 'pitches#display', :as => "display_pitch"
  post 'pitches/:pitch_id/likes', :to => 'likes#create', :as => "pitch_likes"
  get 'pitches/:pitch_id/likes/remember', :to => 'likes#remember', :as => "remember_pitch_likes"
  post 'pitches/:pitch_id/comments', :to => 'comments#create', :as => "pitch_comments"
  

  resource :pitch do
    get 'remember'
  end
  match '/pitch/check_identifier_availibility' => 'pitches#check_identifier_availibility'

  
  resources :seo_settings 

  resources :pitch_requests, :only => [:new, :create]

  resources :home, :only => [:index, :show] do
    collection do 
      get 'failure'
    end
  end
  resources :polls, :only => [:create]
  
  resources :companies, :only => [:update] 
  resources :contacts, :only => [:create]
  
  devise_scope :user do 
    match "/change-password" => 'registrations#change_password' ,:as => :change_password
  end


  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'home#failure'
  match '/contact-us' => 'contacts#new', :as => :contact_us
  match '/need-for-elevator-pitch' => "home#why_pitch", :as => :why_pitch
  match '/elevator-pitch-framework' => "home#elevator_pitch_framework", :as => :elevator_pitch_framework
  match '/how_it_works' => "home#how_it_works", :as => :how_it_works 
  match '/registration_successful' => "home#registration_successful", :as => :registration_successful
  match '/lookup' => "search#lookup", :as => :lookup

  ################## OLD ROUTES - START #################
   match '/why-pitch' => redirect("/elevator-pitch-framework")

  ################## OLD ROUTES - END #################

  
  root :to => 'home#index'
  get '/:clicked_tag', :to => 'home#index', :as => 'tag_search'



end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  
  after_create :notify_new_comment
  
  
  def notify_new_comment
    all_commenter_ids = Comment.where(:commentable_id => self.commentable_id).uniq.pluck(:user_id)
    commenter_emails =  User.where("id in (#{all_commenter_ids.join(',')})").uniq.pluck(:email)
    if commenting_on_self_pitch?
      CommentNotifications.delay.notify_all_commenters(self,commenter_emails)
    else
      CommentNotifications.delay.notify_pitcher(self)
      CommentNotifications.delay.notify_all_commenters(self,commenter_emails)
    end
  rescue
    nil
  end

  private
  def commenting_on_self_pitch?
    self.user_id == self.commentable.user.id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::Helpers::TextHelper
  
  before_filter :authenticate_user!, :populate_pitch

  def create
    @comment_instance = @pitch.comments.new
    @comment_instance.user_id = current_user.id
    @comment_instance.comment = params[:comment][:comment]
    
    if @comment_instance.save
      respond_to do |format|
        format.json {render :json => {:comment => simple_format(@comment_instance.comment), :comment_timestamp => @comment_instance.created_at.strftime(COMMENT_TIME_FORMAT), :commentator_name => @comment_instance.user.name}.to_json}
        format.html {render :text => "Sucessfully created a comment"}
      end
    else
      respond_to do |format|
        status = :unprocessable_entity
        format.json {render :json => {:error => @comment_instance.errors.full_messages.first}.to_json, :status => status}
        format.html {render :text => "Erorr while creating the comment", :status => status}
      end
    end
  end
end

app/views/comments/list.html.erb
<h3 class="set-user-padding comments-heading">All Comments</h3>
<% if @comments.present?  %>
  <% @comments.each_with_index do |comment_instance, index| %>
    <h4 class="comment-index">Comment # <em><%= index + 1 %></em></h4>
    <div class="top-spacer comment-item">
      <div>	
        <span class="comment-author"><%= comment_instance.user.name %></span>
        <br/>
        <span class="post-timestamp"><%= comment_timestamp(comment_instance) %></span>
      </div>
      <div class="comment-text">
       <%= simple_format(h(comment_instance.comment)) %>
      </div>
    </div>
  <% end %>
<% else %>
 <div class="no-comments">
   <p>No comments yet.</p>
   <p class="highlight">You can be the first one to comment.</p>
 </div>
<% end %>
<div class="comments-endpoint"></div>

app/views/comments/login_cover.html.erb
<div class="white-cover align-center login-callout">
  <span>
	<h2>Want to add a comment?</h2>
    <%= hidden_field_tag :pitch_callback_url, remember_pitch_path %>
    Connect with
    <%= link_to(image_tag('facebook_login.png'), "/auth/facebook", :class => 'pitch-callback-url') %>
    or
    <%= link_to(image_tag('twitter_login.png'), "/auth/twitter", :class => 'pitch-callback-url') %>
    or
    <%= link_to("Sign In", new_user_session_path, :class => 'pitch-callback-url btn btn-primary') %>
  </span>
</div>

app/views/comments/new.html.erb
<h4 class="add-comment-callout">Add comment</h4>
<%= form_for(:comment, :url => pitch_comments_path(@pitch.identifier, :format => :json), :html => {:id => "new-comment-form"}) do |f| %>
  <%= f.text_area(:comment, :cols => "35", :rows => "2", :class => "comment-text-area", :placeholder => "Make a good suggestion or simply share your opinion.") %>
  <%= f.submit "Post Comment", :class => "btn btn-primary post-comment-button" %>
<% end %>