config/routes.rb
ElevatorPitch::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  get 'pitches/:identifier', :to => 'pitches#display', :as => "display_pitch"
  post 'pitches/:pitch_id/likes', :to => 'likes#create', :as => "pitch_likes"
  get 'pitches/:pitch_id/likes/remember', :to => 'likes#remember', :as => "remember_pitch_likes"
  post 'pitches/:pitch_id/comments', :to => 'comments#create', :as => "pitch_comments"
  

  resource :pitch do
    get 'remember'
  end
  match '/pitch/check_identifier_availibility' => 'pitches#check_identifier_availibility'

  
  resources :seo_settings 

  resources :pitch_requests, :only => [:new, :create]

  resources :home, :only => [:index, :show] do
    collection do 
      get 'failure'
    end
  end
  resources :polls, :only => [:create]
  
  resources :companies, :only => [:update] 
  resources :contacts, :only => [:create]
  
  devise_scope :user do 
    match "/change-password" => 'registrations#change_password' ,:as => :change_password
  end


  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'home#failure'
  match '/contact-us' => 'contacts#new', :as => :contact_us
  match '/need-for-elevator-pitch' => "home#why_pitch", :as => :why_pitch
  match '/elevator-pitch-framework' => "home#elevator_pitch_framework", :as => :elevator_pitch_framework
  match '/how_it_works' => "home#how_it_works", :as => :how_it_works 
  match '/registration_successful' => "home#registration_successful", :as => :registration_successful
  match '/lookup' => "search#lookup", :as => :lookup

  ################## OLD ROUTES - START #################
   match '/why-pitch' => redirect("/elevator-pitch-framework")

  ################## OLD ROUTES - END #################

  
  root :to => 'home#index'
  get '/:clicked_tag', :to => 'home#index', :as => 'tag_search'



end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
  require 'bitly'
  attr_accessible :description, :tags, :is_active, :user, :embed_code, :category_id,:identifier

  acts_as_commentable


  #########################  Associations  #####################
  belongs_to :user
  belongs_to :category
  has_many :likes, :dependent => :destroy
  has_many :pitch_versions, :dependent => :destroy
  has_one :seo_setting, :dependent => :destroy

  #########################  delegations  #####################
  delegate :company_present?, :email, :name, :add_link, :to => :user

  #########################  Validations  ######################
  validates :description , :presence => { :message => "^Your Pitch can't be blank" }
  validates :tags, :presence => {:message => "^Please tag your pitch"}
  validates :category, :presence => {:message => "^Please choose the pitch category"}

  ###################### Callbacks #########################
  before_create :set_identifier, :set_bitly_url
  before_validation :set_embed_code_info 
  before_save :create_version_if
  after_save :reindex_tags

  ##################### Constants ###########################
  PER_PAGE = 25
  SORT_TYPE_LIKE = "likes"
  SORT_TYPE_CREATED_AT = "created_at"
  EMBED_CODE_ERROR = "Invalid embed code. Please ensure you are entering the embed code and not URL."

  ##################### Scopes ###########################
  scope :sample, where(:sample => true)

  scope :active, where(:is_active => true)

  scope :include_user, includes(:user)

  scope :include_comments, includes(:comments)

  scope :include_likes, includes(:likes)

  scope :join_comments, joins(" LEFT JOIN comments ON pitches.id = comments.commentable_id AND comments.commentable_type = 'Pitch'")

  scope :join_likes, joins(" LEFT JOIN likes ON pitches.id = likes.pitch_id")

  scope :total_likes, select("pitches.*, COUNT(DISTINCT(likes.id)) AS total_likes, COUNT(DISTINCT(comments.id)) AS total_comments")

  scope :group_by_id, group("pitches.id")

  scope :sort_total_likes, order('total_likes DESC, pitches.created_at DESC')

  scope :sort_created_at, order('pitches.created_at DESC, total_likes DESC')
  
  scope :pitch_in, lambda { |ids| where("pitches.id in (?)", ids ) }

  scope :pitch_for, lambda {|category_id| where("pitches.category_id = ?", category_id)}
  ##################### Public ###########################

  class << self

    def sorted_pitches_according_to_total_likes
      tryhash = {}
      idset = []
      a = Pitch.where(:is_active => true).select("id, user_id")
      a.each { |r| tryhash.store( r.id, r.user.total_likes ) }
      tryhash.sort_by {|a,b| b}.reverse.each{|e| idset << e[0] }
      return idset
    end

    def list(hash = {:sort_by => "likes",:page => 1, :per_page => PER_PAGE})
      scope = total_likes.active.include_user.join_likes.join_comments.include_likes.group_by_id
      unless hash[:tags].blank?
        pitch_ids = $redis.smembers(hash[:tags].downcase.squish).collect{|i| i.to_i}
        scope = scope.pitch_in(pitch_ids) unless pitch_ids.blank?
      end
      unless hash[:category_id].blank?
        scope = scope.pitch_for(hash[:category_id])
      end
      scope = hash[:sort_by] == "created_at" ? scope.sort_created_at : scope.sort_total_likes
      scope.paginate(:page => hash[:page], :per_page => hash[:per_page])
    end
    
    def find_by_tags(tags = "")
      return [] if tags.blank?
      pitch_ids = []
      tags.split(",").each do |tag|
        pitch_ids = pitch_ids + $redis.smembers(tag.downcase.squish).collect{|i| i.to_i}
      end
      Pitch.find(pitch_ids.uniq)
    end

    def  sample_list
      sample
    end

    def total
      count
    end

    def rank(user)
      entries = select("pitches.user_id, COUNT(DISTINCT(likes.id)) total_likes").join_likes.sort_total_likes.group_by_id.all
      uniq_entries = entries.collect{|pitch| pitch['total_likes']}.uniq
      user_rank_map = {}

      entries.each do |entry|
        user_rank_map[entry['user_id']] = (uniq_entries.index(entry['total_likes']) + 1)
      end
      
      user_rank_map[user.id] || 0
    end
  end #end of the self block

  def set_me_false
    self.is_active = false
    self.save
  end

  def set_bitly_url()
    Bitly.use_api_version_3
    client = Bitly.new("idyllicsoftware", "R_b5a7ab5f7966ec86f0cde7f4a7e6b393")
    link = "http://#{SiteConfig.app_base_url}/pitches/#{self.identifier}"
    bitly = client.shorten(link) rescue link 
    self.bitly_url = bitly.short_url
  rescue Exception => e
    puts e.message
    puts e.backtrace
  end

  def seo_settings_configured?
    self.seo_setting.present?
  end

  def comments_count
    (self.total_comments || comments.size) rescue comments.size
  end

  def likes_count
    self.likes.size
  end

  def liked?(user)
    self.likes.select{|like| like.user_id == user.id}.first rescue false
  end

  def my_pitch?(user)
    user && self.user_id == user.id
  end

  def video_exists?
    embed_url.present?
  end
  
  def tag_list(downcase = true)
    return [] if tags.blank?
    tags.split(",").collect{|tag| tag.downcase.squish}
  end

  def just_created?
    Time.now  - self.created_at < 90
  end

  def seo_setting_configured?
    !self.seo_setting.nil?
  end
  

  ###################### Private ###########################
  private
  def set_identifier
    return unless self.identifier.blank?
    pass = Devise.friendly_token[0,20] 
    while !Pitch.where(:identifier => pass).first.blank?
      pass = Devise.friendly_token[0,20]
    end    
    self.identifier = Devise.friendly_token[0,20]
  end

  def create_version_if
    if !(self.new_record?) && self.description_changed?()
      version = self.pitch_versions.build(:description => self.changes['description'].first)
      version.save!
    end
  end

  def set_embed_code_info
    if self.embed_code.present?
      set_embed_url
      set_computer_width
      set_computer_height
      set_phone_width
      set_phone_height
    end
  rescue
      self.errors[:embed_code] << EMBED_CODE_ERROR if self.errors[:embed_code].blank?
  end

  def set_embed_url
    self.embed_url = self.embed_code.scan(/http\:\/\/.*?(?=")/i).first
  rescue
    self.errors[:embed_code] << EMBED_CODE_ERROR
  end

  def set_computer_width
    self.computer_width = 230
  end

  def set_computer_height
    self.computer_height = calculate_computer_height
  end

  def set_phone_width
    self.phone_width = 230
  end

  def set_phone_height
    self.phone_height = calculate_phone_height
  end

  def calculate_computer_height()
    width = parse_width
    height = parse_height
    calculate_height(self.computer_width, width, height)
  end

  def calculate_phone_height()
    width = parse_width
    height = parse_height
    calculate_height(self.phone_width, width, height)
  end

  def parse_height
    height_text = self.embed_code.scan(/(height=("|').*?"|'(?=\s))/i).first.first
    height_text.gsub(/[height]/, '').gsub(/["']/, '').gsub(/=/, '').strip.to_i
  end

  def parse_width
    width_text = self.embed_code.scan(/(width=("|').*?"|'(?=\s))/i).first.first
    width_text.gsub(/[width]/, '').gsub(/["']/, '').gsub(/=/, '').strip.to_i
  end

  def calculate_height(reference_width, width, height)
    ((reference_width * height)/width).to_i
  end
  
  def reindex_tags
    tag_list = Pitch.find(self.id).tag_list
    tag_list.each do |tag|
      $redis.srem(tag, self.id.to_s)
      $redis.del(tag) if $redis.smembers(tag).empty?
    end
    self.tag_list.each do |tag|
      $redis.sadd(tag, self.id.to_s)
    end
  rescue Exception => e
    puts e.backtrace
    true
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_filter :authenticate_user!, :except => [:display, :remember]
  before_filter :check_created_pitch, :only => [:new, :create, :edit, :update, :show]
  before_filter :fetch_sample_pitches, :only => [:new, :create, :edit, :update]
  before_filter :load_categories, :only => [:edit, :update, :new, :create]

  def new
    @pitch = current_user.build_pitch()
  end

  def create
    @pitch = current_user.build_pitch(params[:pitch])
    set_pitch_status
    @pitch.save!
    redirect_to(new_seo_setting_path(:identifier => @pitch.identifier))
  rescue ActiveRecord::RecordInvalid
    render :action => "new"
  end

  def edit
    @pitch = current_user.pitch
  end

  def update
    @pitch = current_user.pitch
    @pitch.attributes = params[:pitch]
    set_pitch_status
    @pitch.save!
    if @pitch.seo_setting_configured?
      redirect_to(pitch_path)
    else
      redirect_to(new_seo_setting_path(:identifier => @pitch.identifier))
    end
  rescue ActiveRecord::RecordInvalid
    render :action => "edit"
  end

  def show
    @pitch = current_user.pitch
    @comments = @pitch.comments
  end

  def remember
    session[:pitch_callback_url] = params[:pitch_callback_url]
    render :text => "Sucessfully remembered the pitch location!"
  end

  def display
    @pitch = Pitch.find_by_identifier(params[:identifier])
    if @pitch
      @comments = @pitch.blank? ? [] : @pitch.comments
      render "show"
    else
      redirect_to root_path, :flash => { :error => "Unable to locate that pitch." }
    end
  end

  def check_identifier_availibility
    respond_to do |format|
      available = params[:identifier].blank? ? false : Pitch.find_by_identifier(params[:identifier]).nil?
      format.json {render :text => available ? "<em class='pass'>available</em>" : "<em class='fail'>not available</em>"}
    end
  end

  private
  def set_pitch_status
    @pitch.is_active = (params[:pitch_status] == "Publish" ? true : false)
  end

  def check_created_pitch
    if action_show? && !current_user.pitch_created?
      redirect_to new_pitch_path
    elsif action_edit_or_update? && !current_user.pitch_created?
      redirect_to new_pitch_path
      return false
    elsif action_new_or_create? && current_user.pitch_created?
      redirect_to edit_pitch_path
    end
  end

  def fetch_sample_pitches
    @sample_pitches = Pitch.sample_list
  end

  def load_categories
    @categories = Category.all
  end


end

app/helpers/pitches_helper.rb
module PitchesHelper
  def video_tag(pitch)
    width = mobile_device? ? pitch.computer_width : pitch.phone_width
    height = mobile_device? ? pitch.computer_height : pitch.phone_height
    "<iframe width='#{width}' align='left' height='#{height}' src='#{pitch.embed_url}' frameborder='0' allowfullscreen></iframe>".html_safe
  end
end

app/views/pitches/_form.html.erb
<h1 class="elevator-pitch">What do you do?</h1>
<h2 class="elevator-pitch-tagline ">Be <em>Clear</em>, <em>concise</em> and <em>compelling</em>.</h2>

<div class="getting-started">
  <h2>Alright. Let us help you get started.
    <em>Answer the below and put them in order that creates the most compelling message.</em>
  </h2>
  <%= render :partial => 'pitches/getting_started'%>
  <h2 class="ready">Ready to craft your pitch now?</h2>
</div>

<h3 class="new-pitch-heading field-title">Create your pitch.
  <em class="help help-link">Need help getting started?</em>
</h3>

<%= error_messages_for @pitch, @user, :message => "Oops! something went wrong." %>
<div class="pitch-information-unit">
  <div>
    <%= f.text_area :description, :rows => 10, :cols => 80, :class => 'pitch-description',:placeholder => 'If you need help getting started, click the link above that says "Need help getting started?".' %>
    <div class="create-my-pitch">
    <p>
      Finding it hard? Want us to create it?
      <%= link_to 'Ask the expert', new_pitch_request_path, :class => 'btn btn-info' %>
    </p>
  </div>
  </div>
  <div class="word-counter align-right"></div>
  <div class="clearfix"></div>

  <%= render :partial => 'shared/category_field', :locals => {:f => f} %>
  <h4>Tags*<br/><em>Words that describe what you do?</em></h4>
  <%= f.text_area :tags, :rows => 2, :cols => 80, :class => 'pitch-tags',:placeholder => 'marketing, branding, advertising' %>
  <%= hidden_field_tag :pitch_status, "" %>

  <div>
	  <h4>Youtube embed code <br/><em>This is optional. However, we strongly recommend you add it soon.</em></h4>
    <%= f.text_area :embed_code, :rows => 20, :cols => 80, :class => "embed-code", :placeholder => '<iframe width="560" height="315" src="http://www.youtube.com/embed/i6O98o2FRHw" frameborder="0" allowfullscreen></iframe>' %>
  </div>

  <h4>Custom URL</h4>
  <p>
    <label class="url">http://mindyourpitch.com/pitches/</label><%= f.text_field :identifier, :class => 'url unique_url' %>
    <span id="url_status"><%= image_tag 'load1.gif', :class => 'spinner' %></span>
  </p>
  <div class="clearfix"></div>

  <div class="create-pitch-padding">
    <%= f.submit "Publish", :class => "create-pitch-button" %>
    <span class="align-cancel-link"><%= link_to "Cancel", :back %></span>
  </div>
</div>

app/views/pitches/_getting_started.html.erb
<ul>
  <li>
    <h2>Wow*</h2>
    <p>6 seconds to generate curiosity.</p>
  </li>
  <li class="middle">
    <h2>What*</h2>
    <p>What problem are you solving?</p>
  </li>
  <li>
    <h2>How*</h2>
    <p>How do you solve the problem?</p>
  </li>
</ul>
<ul class="last">
  <li>
    <h2>Why*</h2>
    <p>Why are you passionate this?</p>
  </li>
  <li class="middle">
    <h2>Who</h2>
    <p>Add if you are famous already.</p>
  </li>
  <li>
    <h2>Call to action*</h2>
    <p>Ask to act.</p>
  </li>
</ul>

<h2 class="examples">
  <%= link_to(image_tag('previous.png'), "javascript:void(0)", :class => 'prev') %>
<%= @sample_pitches.count %> Examples
  <%= link_to(image_tag('next.png'), "javascript:void(0)", :class => 'next') %>
</h2>

<div class="sample-pitches">
  <div class="sample-pitch-container">
    <% @sample_pitches.each_with_index do |sample_pitch,index| %>
      <div class="sample-pitch my-pitch-color">
        <h2>
          <%= "#{index + 1}.#{sample_pitch.name}" %>
        </h2>
        <%= simple_format(sample_pitch.description) %>
      </div>
    <% end %>
  </div>
</div>

app/views/pitches/_share_callout.html.erb
<% my_pitch = !@pitch.blank? && @pitch.my_pitch?(current_user) %>	
<% if my_pitch %>	
	<h1 class="elevator-pitch">Spread the word.</h1>	
	<h2 class="elevator-pitch-tagline multi">
	  Ask your friends & family to <em>comment</em> & <em>like</em> your pitch.
	</h2>
	<h2  class="elevator-pitch-tagline multi">
		The more you are liked, the higher you rank..
	</h2>
	<div class="social-information clearfix callout">
	  <%= render :partial => "shared/share_buttons", :locals => {:pitch => @pitch} %>
	</div>
<% end %>

app/views/pitches/edit.html.erb
<%= form_for @pitch, :url => pitch_path(:id => @pitch.identifier), :html => {:method => :put, :id => 'pitch_form'} do |f| %> 
  <div class="new-pitch-unit">
    <%= render :partial => "form", :locals => { :f => f }  %>
  </div>
<% end %> 

app/views/pitches/new.html.erb
<%= form_for @pitch, :url => pitch_path, :html => {:method => :post, :id => 'pitch_form'} do |f| %> 
  <div class="new-pitch-unit">
    <%= render :partial => "form", :locals => { :f => f }  %>
  </div>
<% end %> 

app/views/pitches/show.html.erb
<% content_for :page_header do %>
<title><%= @pitch.seo_setting_configured? ? @pitch.seo_setting.page_title : @pitch.user.name %></title>
  <meta name="Description" content="<%= @pitch.seo_setting_configured? ? @pitch.seo_setting.page_description : @pitch.tags %>" />
<% end %>
<%= render :partial => "shared/social_header" %>
<div class="desc-site site-content pitch-show-page">
   <% my_pitch = !@pitch.blank? && @pitch.my_pitch?(current_user) %>	
   <%= render :partial => 'pitches/share_callout'%>
  <% unless @pitch.blank? %>
    <div class="hero-unit indivisual-pitch <%= 'my-pitch-color' if my_pitch %>">
      <%= render :partial => "shared/pitch/main", :locals => {:pitch => @pitch} %>
      <div class="social-information clearfix">
        <%= render :partial => "shared/pitch/company", :locals => {:pitch => @pitch} %>
        <div class="social-links-right">
          <%= render :partial => "shared/pitch/edit_link", :locals => {:pitch => @pitch} %>
          <%= render :partial => "shared/share_buttons", :locals => {:pitch => @pitch} %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="white-cover align-left">
    <div>
      <%= render :file => "comments/list" %>
    </div>
  </div>
  
  <% if user_signed_in? %>
	<div class="new-comment-wrapper">
		<%= render :file => "comments/new" %>
	</div>
  <%else %>
  	<div>
	   <%= render :file => "comments/login_cover" %>
	</div>
  <%end %>
</div>
<% @user = User.new %>
<%= render :partial => "sessions/login_cover" %>