config/routes.rb
ElevatorPitch::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  get 'pitches/:identifier', :to => 'pitches#display', :as => "display_pitch"
  post 'pitches/:pitch_id/likes', :to => 'likes#create', :as => "pitch_likes"
  get 'pitches/:pitch_id/likes/remember', :to => 'likes#remember', :as => "remember_pitch_likes"
  post 'pitches/:pitch_id/comments', :to => 'comments#create', :as => "pitch_comments"
  

  resource :pitch do
    get 'remember'
  end
  match '/pitch/check_identifier_availibility' => 'pitches#check_identifier_availibility'

  
  resources :seo_settings 

  resources :pitch_requests, :only => [:new, :create]

  resources :home, :only => [:index, :show] do
    collection do 
      get 'failure'
    end
  end
  resources :polls, :only => [:create]
  
  resources :companies, :only => [:update] 
  resources :contacts, :only => [:create]
  
  devise_scope :user do 
    match "/change-password" => 'registrations#change_password' ,:as => :change_password
  end


  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'home#failure'
  match '/contact-us' => 'contacts#new', :as => :contact_us
  match '/need-for-elevator-pitch' => "home#why_pitch", :as => :why_pitch
  match '/elevator-pitch-framework' => "home#elevator_pitch_framework", :as => :elevator_pitch_framework
  match '/how_it_works' => "home#how_it_works", :as => :how_it_works 
  match '/registration_successful' => "home#registration_successful", :as => :registration_successful
  match '/lookup' => "search#lookup", :as => :lookup

  ################## OLD ROUTES - START #################
   match '/why-pitch' => redirect("/elevator-pitch-framework")

  ################## OLD ROUTES - END #################

  
  root :to => 'home#index'
  get '/:clicked_tag', :to => 'home#index', :as => 'tag_search'



end

app/views/shared/_category_field.html.erb
<h4>Category*<br/><em>What is your purpose?</em></h4>
<div>
  <% @categories.each do |category| %>
    <div class="category">
      <p class="title">
        <%= f.radio_button 'category_id', category.id %>
        <%= category.title %>
      </p>
      <p class="description">
        <%= category.description%>
      </p>
    </div>
  <% end %>
</div>

app/views/shared/_poll.html.erb
<% if @question.present?  %>
  <div class="poll">
    <%= form_for(:poll_result, :url => polls_path(:format => :json), :html => {:id => "poll_form"}) do |f| %>
      <label>
        <%= simple_format(@question.description) %>
        <%= f.hidden_field :poll_question_id, :value => @question.id %>
      </label>
      <ul class="nav nav_links_color">
        <% @question.poll_answers.each do |answer| %>
          <li>
            <%= link_to(simple_format(answer.description), "javascript:void(0)", :class => "btn", :'data-val' => answer.id) %>
          </li>
        <% end %>
        <%= f.hidden_field :poll_answer_id %>
      </ul>
    <% end %>
  </div>
  <div class="shadow-image"><%= image_tag("/assets/shadow.png") %> </div>
<% end %>

app/views/shared/_share_buttons.erb
<div class="social-links-right">
  <% sharelink_url = "http://#{SiteConfig.app_base_url}#{display_pitch_path(:identifier => pitch.identifier)}" %>
  <ul>
    <li>
      <%= tweet_button( :url => pitch.bitly_url, :text => get_tweet_text(pitch.description) ) %> <%# shdnt be a space betn "tweet button" and opening bracket "(" - otherwise Error %>
    </li>
    <li> | </li>
    <li>
      <%= link_to(image_tag("fb_share.png", :class => "align-vertically-fb"), "javascript:void(0);",
        :class => "fb-share-link",
        :'fb-post-link' => sharelink_url,
        :'fb-logo' => "http://#{SiteConfig.app_base_url}/assets/logo.png",
        :'fb-description' => pitch.description,
        :'fb-title' => pitch.user.name
      ) %>
    </li>
    <li>
      |
    </li>
    <li>
      <script type="IN/Share" data-counter="right" data-url="<%= sharelink_url %>"></script>
    </li>
    <li>
      |
    </li>
    <li>
    <g:plusone size="medium" href="<%= sharelink_url %>"></g:plusone>
    </li>
  </ul>
</div>

app/views/shared/_social_header.erb
<div id="fb-root"></div>
<script src='http://connect.facebook.net/en_US/all.js'></script>
<script type="text/javascript">
  FB.init({appId: "<%= FACEBOOK_CONFIG[:app_id] %>", status: true, cookie: true});

  function postToFeed(postLink, logo, description, title) {

    // calling the API ...
    var obj = {
      method: 'feed',
      link: postLink,
      picture: logo,
      name: title + ' @mindyourpitch',
      caption: 'How is that?',
      description: description
    };

    function callback(response) {
      document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
    }

    FB.ui(obj, callback);
    return false;
  }
</script>

<%# Twitter %>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<%# Google+ %>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<%# inshare %>
<%#*<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>%>
<%#*<script type="IN/Share" data-counter="right"></script>%>