config/routes.rb
ElevatorPitch::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

  get 'pitches/:identifier', :to => 'pitches#display', :as => "display_pitch"
  post 'pitches/:pitch_id/likes', :to => 'likes#create', :as => "pitch_likes"
  get 'pitches/:pitch_id/likes/remember', :to => 'likes#remember', :as => "remember_pitch_likes"
  post 'pitches/:pitch_id/comments', :to => 'comments#create', :as => "pitch_comments"
  

  resource :pitch do
    get 'remember'
  end
  match '/pitch/check_identifier_availibility' => 'pitches#check_identifier_availibility'

  
  resources :seo_settings 

  resources :pitch_requests, :only => [:new, :create]

  resources :home, :only => [:index, :show] do
    collection do 
      get 'failure'
    end
  end
  resources :polls, :only => [:create]
  
  resources :companies, :only => [:update] 
  resources :contacts, :only => [:create]
  
  devise_scope :user do 
    match "/change-password" => 'registrations#change_password' ,:as => :change_password
  end


  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'home#failure'
  match '/contact-us' => 'contacts#new', :as => :contact_us
  match '/need-for-elevator-pitch' => "home#why_pitch", :as => :why_pitch
  match '/elevator-pitch-framework' => "home#elevator_pitch_framework", :as => :elevator_pitch_framework
  match '/how_it_works' => "home#how_it_works", :as => :how_it_works 
  match '/registration_successful' => "home#registration_successful", :as => :registration_successful
  match '/lookup' => "search#lookup", :as => :lookup

  ################## OLD ROUTES - START #################
   match '/why-pitch' => redirect("/elevator-pitch-framework")

  ################## OLD ROUTES - END #################

  
  root :to => 'home#index'
  get '/:clicked_tag', :to => 'home#index', :as => 'tag_search'



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :populate_question
  before_filter :authenticate_user!, :only => [:show]
  
  def index
    @pitches = Pitch.list(:tags => tags,:page => params[:page], :per_page => Pitch::PER_PAGE, :sort_by => params[:sort_type], :category_id => params[:category_id])
    respond_to do |format|
      format.json {render :json => {:page => params[:page], :content => render_to_string(:layout => false, :partial => "home/pitches.html.erb")}}
      format.html{render :action => "index"}
    end
  end

  def elevator_pitch_framework
    @sample_pitches = Pitch.sample_list
  end

  #this method is used for redirection when a 401 unauthorised callback is 
  #received from twitter. configurations in config/initializers/omniauth.rb
  def failure
    redirect_to new_user_session_path, :flash => { :error => "Operation Cancelled" }
  end

  private
  def populate_question
    if user_signed_in?
      @question = PollQuestion.random(current_user)
    end
  end

  def tags
    return params[:tags] if !params[:tags].blank?
    unless params[:clicked_tag].blank?
      return params[:clicked_tag].gsub('-', ' ')
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  require 'bitly'
  
  # this method will return the shortened url to be shared on twitter using Bitly api
  def get_short_url(link)
    client = Bitly.client
    shortened_url = client.shorten(link)
    return shortened_url.short_url 
  end

  # this method will return the text of the pitch to be shared on twitter using Bitly api
  def get_tweet_text(text)
    return sanitize(strip_tags(strip_links(text))).split("\r\n").join[0..99]
  end

  def my_pitch_class(pitch)
    return "my-pitch-color" if pitch.my_pitch?(current_user)
  end
end

app/views/home/_category.html.erb
<div class="category">
  <div class="btn-group" data-toggle="buttons-radio">
	<button type="button" class="btn-success btn" data-reset-text="All" data-loading-text="Loading..." value="">All pitches</button>
	<% all_categories.each do |category| %>
	  <button type="button" class="btn" data-reset-text="<%= category.title %>" data-loading-text="Loading..." value="<%= category.id %>"><%= category.title %> Pitches</button>
	<% end %>
	<%= hidden_field_tag :pitch_type, "" %>	
  </div>
</div>

app/views/home/_pitches.html.erb
<%= render :partial => "shared/social_header", :handlers => [:erb] %>
<% if @pitches.blank? %>
  <div class="empty-results">
    Oops! We did not find anything based on your search criteria.<br/>Try some other criteria.
  </div>
<% else %>
  <% page_number =  params[:page] || 1 %>
  <div class="page-<%= page_number %>">
    <% @pitches.each do |pitch| %>
      <div class="hero-unit indivisual-pitch <%= my_pitch_class(pitch) %>">
        <%= render :partial => "shared/pitch/main", :locals => {:pitch => pitch}, :handlers => [:erb] %>
        <div class="social-information clearfix">
          <%= render :partial => "shared/pitch/company", :locals => {:pitch => pitch}, :handlers => [:erb] %>
          <%= render :partial => "shared/share_buttons", :locals => {:pitch => pitch}, :handlers => [:erb] %>
          <div class="comments-count">
            <ul>
              <li>
                <%= render :partial => "shared/pitch/edit_link", :locals => {:pitch => pitch}, :handlers => [:erb] %>
              </li>
              <li>
                <%= link_to pluralize(pitch.comments_count, "comment"), display_pitch_path(:identifier => pitch.identifier)  %>
              </li>
              <li> | </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/home/_quotes.html.erb
<div class="description">
    <p>You have less than one minute to answer "What you do?". Your audience knows nothing about your business, you passion or your goals. Are you prepared? Can you present it in the most compelling way to want them to know more?
	<br/><br/>Take the first step today. <%= link_to 'Get started!', (user_signed_in? ? edit_pitch_path : new_user_registration_path) %>
	</p>
</div>

app/views/home/_search.html.erb
<div class="search">
	<input type="text" name="query" id="searchBox" class="searchBox" placeholder = 'Search tags: marketing' data-provide="typeahead"></input>
</div>

app/views/home/_slogan.html.erb
<div class="elevator-pitch-container">
  <%= render :partial => "home/quotes" %>
  <div class="pitch-advantage">
    <h3 class="title">In 1 minute you can:</h3>
    <ul>
      <li>Deliver a killer <em>Shark tank pitch</em></li>
      <li>Create right <em>business messaging</em></li>
      <li>Communicate your <em>vision statement</em></li>
      <li>Construct a mind glueing <em>cover letter</em></li>
      <li>Be <em>Clear</em>, <em>Concise</em> and <em>Compelling</em></li>
      <li class="last">and more...</li>
    </ul>
  </div>
  
  
</div>

app/views/home/_sort.html.erb
<div class="button-container filter">
  <div class="btn-group" data-toggle="buttons-radio">
    <button type="button" class="btn-success btn" data-reset-text="Most Liked" data-loading-text="Loading..." value="<%= Pitch::SORT_TYPE_LIKE %>">Most Liked</button>
    <button type="button" class="btn" data-reset-text="Most Recent" data-loading-text="Loading..." value="<%= Pitch::SORT_TYPE_CREATED_AT %>">Most Recent</button>
    <%= hidden_field_tag :sort_type, "" %>
  </div>
</div>

app/views/home/elevator_pitch_framework.html.erb
<% content_for :page_header do %>
<title>Elevator pitch framework | Mind Your Pitch</title>
  <meta name="Description" content="Elevator pitch builder tool for helping you get started to create your elevator pitch." />
<% end %>

<div class="new-pitch-unit elevator-pitch-framework-unit">
  <div class="elevator-pitch-framework">
    <h2>Elevator Pitch Framework
       <em>Getting started with your elevator pitch.</em>
    </h2>
    <p class="description">
      Every pitch must have its individuality. The below framework helps you get started. The order is not important. Answer the questions in below blue box and arrange them in the most compelling manner.
      <br/><br/>
      <em>Don't worry if you still cannot find words, we'll help you build your pitch once you register and send us a request.</em>
    </p>
    <%= render :partial => 'pitches/getting_started'%>
    <div class="cta">
      <% if current_user %>
        <%= link_to 'Ready to craft your pitch now?' , (current_user.pitch_created? ? edit_pitch_path : new_pitch_path) , :class => " signup-button" %>
      <% else %>
        <%= link_to 'Ready to craft your pitch now?' , new_user_registration_path, :class => " signup-button" %>
      <% end %>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="clearfix"></div>

app/views/home/how_it_works.html.erb
Home#HowItWorks

app/views/home/index.html.erb
<% content_for :page_header do %>
<title><%= params[:clicked_tag].blank? ? 'We help you build your Elevator Pitch' : "#{params[:clicked_tag]} elevator pitches"%> | Mind Your Pitch</title>
  <meta name="Description" content="Pitching platform to collaborate towards building a perfect pitch.Only social platform that helps you create your business pitch clearly, concisely and in a compelling way." />
  <meta name="keywords" content="Elevator pitch, Business pitch, Vision statement, Shark tank pitch, Cover letter." />
<% end %>

<div id="pitchFilters" class="actions">
  <h2>What kind of elevator pitch would you like to see?</h2>
  <%= render :partial => 'home/search' %>
  <div class="filter-sort">
    <%= render :partial => "home/sort" %>
    <%= render :partial => "home/category" %>
    <%= hidden_field_tag :search_filter_url, root_path(:format => :json)  %>
  </div>
</div>


<div class="pitch-loading">
  <%= image_tag 'horizontal-loading.gif' %>
</div>
  
<div class="site-content">
  <div id="results">
    <%= render :partial => 'pitches' %>
  </div>

  <p id="loading" class="align-loader">
    Loading more pitches !!!
    <%= image_tag "load1.gif" %>
  </p>

  <%= will_paginate @pitches  %>
</div>

<% @user = User.new %>
<%= render :partial => "sessions/login_cover" %>

<% unless params[:clicked_tag].blank? %>
  <script type="text/javascript">
    $(document).ready(function(){
      $.scrollTo( $('#pitchFilters').offset().top - 100 ,400);
    });
  </script>
<% end %>

app/views/home/registration_successful.html.erb
<div class="site-content">
  <div class="hero-unit hero-unit-successful-sign-up">
    <h2>Thank you for signing up. <span class="hero-unit-successful-sign-up-sub">You’re almost there.</span></h2>
    <div class="successful-sign-up-message">
      Confirmation email is on its way. Click on the link in that email to verify yourself and get started.<br/>
      Make sure to check your <u>spam</u> folder.
    </div>
    <div class="successful-sign-up-confirmation"><i>Did not get an email?</i></div>
    <div class="successful-sign-up-confirmation-button">
      <%= link_to "Resend Confirmation Email", new_confirmation_path(:user), :class => "signin-button resend-confirmation-button" %><br />
    </div>
  </div>
</div>

app/views/home/why_pitch.html.erb
<% content_for :page_header do %>
<title>Why Elevator Pitch? | Mind Your Pitch</title>
  <meta name="Description" content="Goal of an elevator pitch is to generate curiosity, not to sell or generate leads. It should communicate your vision statement in the right spirit and entice the listener to want to know more." />
  <meta name="keywords" content="Pitch builder, Pitching the perfect pitch, Simon Sinek" />
<% end %>
<div class="whyPitch">
  <h3 class="why-pitch-heading"> Why Pitch </h3>
  <p>You certainly understand the immediate advantage of having a pitch ready for sales reasons. However working on your pitch is much more than just driving sales.</p>
  <br/>

  <ol>
    <li><span class="why-pitch-sub-headers">LESS IS MORE</span>
      <br/>
      <p>
        <em>“A quote is always well understood than a novel!”</em>
        <br/><br/>
        Since you only have a few words, you are guaranteed to have full attention of your audience for that span. 
        Carefully crafted pitch can make:
        <ul>
          <li>a good first impression</li>
          <li>saves time for your audience and hence quickens the decision making process.</li>
        </ul>
      </p>
    </li>

    <br/>

    <li><span class="why-pitch-sub-headers">COMMUNICATE THE WHY</span>
      <br/>
      <p>
        <em>“The goal of any business is to make money. Wrong!”</em>
        <br/><br/>
        The time has changed and you need a much more conscious reason for your existence in order to reach the peak. 
        <ul>
          <li>The more you work on bettering your pitch, the more you come closer to realize your purpose.</li>
          <li>The more you learn about your purpose, better you become on your messaging.</li>
          <li>The better you become on your messaging, more you convert and grow.</li>
        </ul>
        <br/>
        Simon sinek rightly puts it <em>“People buy WHY you do and not the WHAT you do”</em>. 
        Watch this video NOW if you haven’t already seen it. 
      </p>
      <br/><br/>
      <iframe width="560" height="315" src="http://www.youtube.com/embed/qp0HIF3SfI4" frameborder="0" allowfullscreen></iframe></iframe>
    </li>

    <br/>

    <li><span class="why-pitch-sub-headers">KNOW THY BUSINESS BETTER</span>
      <br/>
      <p>
        <em>“Know your purpose!”</em>
        <br/><br/>
        Most businesses do not start with a vision, however ideal it is. You start a business and as time goes, things become clearer. 
        When you work on your pitch, you ask yourself constantly, why do I exist? 
        Answering that question itself helps you understand your purpose better. 
    </li>

    <br/>

    <li><span class="why-pitch-sub-headers">BE READY</span>
      <br/>
      <p>
        <em>“Be Prepared!”</em>
        <br/><br/>
        When the time comes and you happen to be in the right place, you want to be fully prepared to meet your big opportunity. 
        Preparing your pitch is the first step towards being prepared.
        So get started immediately.
      </p>
    </li>
  </ol>

  <div class="why-pitch-create-pitch-button">
    <%= link_to "Create your pitch", new_user_registration_path, :class => "signup-button" %>
  </div>
</div>